services:
  # nettemplate.mssql:
  #   image: "mcr.microsoft.com/mssql/server:2022-latest"
  #   container_name: nettemplate_mssql_db
  #   environment:
  #     - SA_PASSWORD=ChangeThis!!1
  #     - ACCEPT_EULA=Y
  #   volumes:
  #     - nettemplate_mssql_data:/var/opt/mssql
  #   healthcheck:
  #       test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "ChangeThis!!1", "-Q", "SELECT 1"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5
  #       start_period: 20s

  # nettemplate.redis:
  #   image: redis:7.2b
  #   container_name: nettemplate_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - nettemplate_redis_data:/data
  #   restart: always
  #   command: redis-server --save 60 1 --loglevel warning
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s
        
  nettemplate.postgres:
    image: postgres:16-alpine
    container_name: nettemplate_postgres_db
    restart: always
    environment:
      POSTGRES_USER: nettemplate_usr
      POSTGRES_PASSWORD: ChangeThis!!1
      POSTGRES_DB: nettemplate_db
    ports:
      - "5432:5432"
    volumes:
      - nettemplate_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  nettemplate.api:
    image: ${DOCKER_REGISTRY-}nettemplateapi
    container_name: nettemplate_api
    restart: unless-stopped
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: src/NetTemplate.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/Buenos_Aires
     # - ConnectionStrings__DefaultConnection=Server=nettemplate_mssql_db,1433;Database=NetTemplateDB;User=sa;Password=ChangeThis!!1;TrustServerCertificate=True;
      - ConnectionStrings__DefaultConnection=Server=nettemplate_postgres_db;Port=5432;Database=nettemplate_db;Username=nettemplate_usr;Password=ChangeThis!!1
      - ApiKeyAuthOptions__SecretToken=SecretTokenToTest123

volumes:
 # nettemplate_mssql_data:
 nettemplate_pg_data:

# docker compose --env-file .env.local up -d
   